#!/usr/bin/env bash
# bootstrap_host.sh — turn a bare VPS into the deploy host deploy-site.sh expects.
#
# deploy-site.sh assumes the host contract (deploy/host-contract.md) already
# exists: a `deploy` user reachable over SSH, /srv/www/realworld/{releases,
# current}, Caddy installed, maintenance.html staged, firewall on. Until now
# that prep was "run once, manually" — this script makes it reviewable and
# repeatable, and doubles as the disaster-recovery rebuild path (a lost host
# is re-provisioned from here + DNS repoint, ~30 min).
#
# SAFE BY DEFAULT: bare invocation PRINTS the plan and writes nothing.
#
#   ./tools/bootstrap_host.sh                    print the host contract + plan
#   ./tools/bootstrap_host.sh --emit <file>      write the root-side provision
#                                                script for review/hand-run
#   ./tools/bootstrap_host.sh --apply            provision over SSH
#                                                (needs RW_BOOTSTRAP_HOST=root@ip)
#   ./tools/bootstrap_host.sh --check            verify a live host meets the
#                                                contract (needs RW_DEPLOY_HOST)
#   ./tools/bootstrap_host.sh --check-local DIR  verify the FS-layout half of the
#                                                contract against a local dir
#                                                (rehearsal / fake-host testing)
set -euo pipefail
cd "$(dirname "$0")/.."

DEPLOY_PATH="${RW_DEPLOY_PATH:-/srv/www/realworld}"
DEPLOY_USER="${RW_DEPLOY_USER:-deploy}"

fail() { echo "BOOTSTRAP FAIL: $*" >&2; exit 1; }
ok()   { echo "  ok: $*"; }

# ── the root-side provisioning script (Debian/Ubuntu VPS) ────────────────────
provision_script() {
cat <<EOF
#!/usr/bin/env bash
# host-provision.sh — generated by tools/bootstrap_host.sh ($(date +%F))
# Run ON the VPS as root. Debian/Ubuntu assumed; adjust pkg lines otherwise.
set -euo pipefail

# 1. packages + caddy (official repo, auto-TLS)
apt-get update -y
apt-get install -y caddy ufw rsync curl
systemctl enable --now caddy

# 2. unattended security upgrades (host is single-purpose; auto-patch is safe)
apt-get install -y unattended-upgrades
dpkg-reconfigure -f noninteractive unattended-upgrades || true

# 3. firewall: SSH + HTTP/S only
ufw allow OpenSSH
ufw allow 80/tcp
ufw allow 443/tcp
ufw --force enable

# 4. deploy user (key-only auth; add the owner's pubkey after)
id -u ${DEPLOY_USER} >/dev/null 2>&1 || useradd -m -s /bin/bash ${DEPLOY_USER}
mkdir -p /home/${DEPLOY_USER}/.ssh
chmod 700 /home/${DEPLOY_USER}/.ssh
touch /home/${DEPLOY_USER}/.ssh/authorized_keys
chmod 600 /home/${DEPLOY_USER}/.ssh/authorized_keys
chown -R ${DEPLOY_USER}:${DEPLOY_USER} /home/${DEPLOY_USER}/.ssh

# 5. site layout (deploy-site.sh rsync target + symlink contract)
mkdir -p ${DEPLOY_PATH}/releases
ln -sfn ${DEPLOY_PATH}/releases ${DEPLOY_PATH}/current 2>/dev/null || true
chown -R ${DEPLOY_USER}:${DEPLOY_USER} ${DEPLOY_PATH}

# 6. maintenance page staged OUTSIDE releases (rollback runbook, Caddyfile block)
install -m 644 /tmp/rw-maintenance.html ${DEPLOY_PATH}/maintenance.html 2>/dev/null \
  || echo "NOTE: copy deploy/maintenance.html to ${DEPLOY_PATH}/maintenance.html"

# 7. Caddy config — install the reviewed Caddyfile, then reload
#    scp deploy/Caddyfile root@host:/etc/caddy/Caddyfile && systemctl reload caddy

echo "PROVISION DONE — remaining: add deploy pubkey, install Caddyfile, reload"
EOF
}

check_local() { # verify FS layout under a dir that mimics the host root
  local root="$1" bad=0
  [ -d "$root${DEPLOY_PATH}/releases" ] && ok "releases/ exists" || { echo "  MISSING: $root${DEPLOY_PATH}/releases"; bad=1; }
  [ -e "$root${DEPLOY_PATH}/current" ] && ok "current link present" || { echo "  MISSING: $root${DEPLOY_PATH}/current"; bad=1; }
  [ -f "$root${DEPLOY_PATH}/maintenance.html" ] && ok "maintenance.html staged" || { echo "  MISSING: maintenance.html"; bad=1; }
  [ "$bad" -eq 0 ] && { echo "CHECK-LOCAL PASS ($root)"; return 0; }
  echo "CHECK-LOCAL FAIL ($root)"; return 1
}

check_remote() {
  : "${RW_DEPLOY_HOST:?set RW_DEPLOY_HOST (deploy@host) for --check}"
  echo "== checking host contract on $RW_DEPLOY_HOST =="
  ssh ${RW_DEPLOY_SSH:-} "$RW_DEPLOY_HOST" bash -s <<EOF
set -e
bad=0
chk(){ [ \$1 ] && echo "  ok: \$2" || { echo "  MISSING: \$2"; bad=1; }; }
chk "-d ${DEPLOY_PATH}/releases" "releases/"
chk "-e ${DEPLOY_PATH}/current" "current link"
chk "-f ${DEPLOY_PATH}/maintenance.html" "maintenance.html"
chk "-w ${DEPLOY_PATH}/releases" "releases/ writable by ${DEPLOY_USER}"
command -v caddy >/dev/null && echo "  ok: caddy installed" || { echo "  MISSING: caddy"; bad=1; }
command -v rsync >/dev/null && echo "  ok: rsync installed" || { echo "  MISSING: rsync"; bad=1; }
exit \$bad
EOF
  echo "CHECK REMOTE: exit $?"
}

case "${1:-plan}" in
  --emit)
    [ -n "${2:-}" ] || fail "--emit needs a target file"
    provision_script > "$2"; chmod +x "$2"
    echo "wrote $2 — review it, then run on the VPS as root (see deploy/host-contract.md)";;
  --apply)
    : "${RW_BOOTSTRAP_HOST:?set RW_BOOTSTRAP_HOST=root@<ip> for --apply}"
    echo "== provisioning $RW_BOOTSTRAP_HOST (deploy path $DEPLOY_PATH, user $DEPLOY_USER) =="
    scp ${RW_DEPLOY_SSH:-} deploy/maintenance.html "$RW_BOOTSTRAP_HOST:/tmp/rw-maintenance.html"
    provision_script | ssh ${RW_DEPLOY_SSH:-} "$RW_BOOTSTRAP_HOST" bash -s
    echo "== done. Verify: RW_DEPLOY_HOST=${DEPLOY_USER}@<ip> $0 --check";;
  --check) check_remote;;
  --check-local) [ -n "${2:-}" ] || fail "--check-local needs a dir"; check_local "$2";;
  *)
    cat <<EOF
== bootstrap_host — the "first-time host prep" as code ==

Host contract (full spec: deploy/host-contract.md):
  user      ${DEPLOY_USER} (key-only SSH)
  layout    ${DEPLOY_PATH}/releases/ + current symlink + maintenance.html
  services  caddy (auto-TLS) · ufw (22/80/443) · rsync · unattended-upgrades

Modes:
  bare              this plan — writes nothing
  --emit <file>     write the reviewed-as-root provision script
  --apply           provision over SSH (RW_BOOTSTRAP_HOST=root@<ip>)
  --check           verify a live host (RW_DEPLOY_HOST=deploy@<ip>)
  --check-local DIR verify the FS layout on a local/fake host dir

DR note: a lost host is rebuilt by --apply on a fresh VPS + DNS repoint
(deploy/dns-records.example) — no backup needed, the site is stateless
and every release is reproducible from git (INFRASTRUCTURE.md §12).
EOF
    ;;
esac
