#!/usr/bin/env python3
"""build_recap.py — draft "This Week on the Block" from the spectator archive.

Input: a world-track archive conforming to world/history.json ({"days":
{YYYY-MM-DD: [events]}}) or a flat feed.json-style event list. Output: a
markdown recap following social/drafts/recap-format.md — headline, feed,
residents, numbers, hook, footer.

Honesty rules enforced structurally: only events present in the input are
reported; request numbers come from the events, never estimates; rumor
beats are labeled word-on-the-block, never asserted. A quiet week renders
as a quiet week.

Usage:
  python3 build_recap.py --archive history.json [--from D --to D] [--out FILE]
"""
import argparse, json, re, sys
from collections import Counter

MAINS = {f"C{i}" for i in range(1, 9)}
FINAL_STATUS = {"resolved", "refunded", "not approved", "player session ended"}


def load_events(path):
    data = json.load(open(path))
    if isinstance(data, dict) and "days" in data:
        out = []
        for day in sorted(data["days"]):
            for e in data["days"][day]:
                out.append(dict(e, day=day))
        return out
    if isinstance(data, dict):  # feed.json-style: find the event list
        for key in ("demo_seeds", "events"):
            if key in data:
                return [dict(e, day=None) for e in data[key]]
    if isinstance(data, list):
        return [dict(e, day=None) for e in data]
    raise SystemExit(f"unrecognized input shape in {path}")


def req_key(e):
    """Collapse lifecycle events of one request into a single case."""
    who = e.get("who") or "?"
    text = re.sub(r"\s*·.*$", "", e.get("text", ""))
    text = re.sub(r",?\s*\d+\s*(min|h)\b.*$", "", text)
    return (who, text.strip()[:60])


def pick_headline(events):
    for e in events:  # player-called weather is the strongest beat
        if e["kind"] == "weather" and e.get("who") and e["who"] != "admin":
            text = e["text"]
            return text if "called by" in text else f"{text} — a viewer called it."
    for e in events:
        if e["kind"] == "admin":
            return f"Admin intervention on the block: {e['text']}"
    weather = [e for e in events if e["kind"] == "weather"]
    if len(weather) >= 2:
        return f"{len(weather)} sky changes this week — the block kept the cameras busy."
    scene = [e for e in events if e["kind"] in ("scene", "venue")]
    if scene:
        return scene[len(scene) // 2]["text"] + "."
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--archive", required=True)
    ap.add_argument("--from", dest="frm")
    ap.add_argument("--to", dest="to")
    ap.add_argument("--watch", default="{{WATCH}}")
    ap.add_argument("--out")
    a = ap.parse_args()

    events = load_events(a.archive)
    days = sorted({e["day"] for e in events if e.get("day")})
    if a.frm or a.to:
        events = [e for e in events if e.get("day") and
                  (not a.frm or e["day"] >= a.frm) and
                  (not a.to or e["day"] <= a.to)]
        days = sorted({e["day"] for e in events})
    if not events:
        raise SystemExit("no events in window")
    label = f"{days[0]} → {days[-1]}" if days else "undated feed window"

    cases = {}
    for e in events:
        if e["kind"] == "request":
            cases[req_key(e)] = e  # last lifecycle event wins
    counts = Counter(e.get("status", "?") for e in cases.values())
    filed = len(cases)
    ran = counts["resolved"] + counts["running"]
    refunded = counts["refunded"]

    feed_beats, seen = [], set()
    for e in events:
        if e["kind"] == "request" and e.get("status") in FINAL_STATUS | {"running"}:
            k = req_key(e)
            if k in seen or e.get("status") in {"refunded", "not approved"}:
                continue
            seen.add(k)
            feed_beats.append(f"- @{e.get('who','?')}: {e['text']}")
    resident_beats = [
        f"- {e['text']}" for e in events
        if e["kind"] in ("move", "scene") and
        ({e.get("who")} | set(e.get("mentions") or [])) & MAINS
    ][:3]
    open_rumors = [
        re.sub(r"^Word on the block —\s*", "", e["text"]).rstrip(".")
        for e in events
        if e["kind"] == "rumor" and not (e.get("outcome") or {}).get("state")
    ]
    press = [e["text"] for e in events if e["kind"] == "press"]

    L = [f"<!-- generated by tools/build_recap.py from {a.archive} ({label});",
         "     review before posting — recap-format.md honesty rules apply -->",
         "", f"**This Week on the Block — {label}:**", ""]
    h = pick_headline(events)
    if h:
        L += [h, ""]
    if feed_beats:
        L += feed_beats[:4] + [""]
    if resident_beats:
        L += ["Meanwhile on the block:"] + resident_beats + [""]
    L += [f"{filed} requests filed. {ran} ran. {refunded} refunded — "
          "the feed shows all of it.", ""]
    for p in press[:1]:
        L += [p, ""]
    if open_rumors:
        L += [f"Still unconfirmed on the block: {open_rumors[-1]}.", ""]
    L += [f"Watch free: {a.watch}", "",
          "_Numbers pulled from the public request feed. Quiet beats reported"
          " as quiet. Nothing invented._"]

    out = "\n".join(L)
    if a.out:
        open(a.out, "w").write(out + "\n")
        print(f"wrote {a.out} ({len(events)} events, {filed} request cases)",
              file=sys.stderr)
    else:
        print(out)


if __name__ == "__main__":
    main()
