#!/usr/bin/env python3
"""Generate site/css/tokens.css from site/assets/brand-tokens.json.

tokens.css is the importable form of the brand palette/type for any surface
that can't share style.css (emails, embeds, future microsites). style.css
already defines the same custom properties inline — this file must never
diverge from it; tools/brand_audit.py enforces parity.

Run: python3 marketing/tools/make_tokens.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOKENS = os.path.join(ROOT, "site", "assets", "brand-tokens.json")
OUT = os.path.join(ROOT, "site", "css", "tokens.css")

HEADER = """/* GENERATED by tools/make_tokens.py from assets/brand-tokens.json — do not
   edit by hand. Edit the JSON (and BRAND.md §5/§6) and regenerate.
   The --rw-* names mirror style.css's unprefixed tokens; both stay in sync
   via tools/brand_audit.py. */"""


def main():
    data = json.load(open(TOKENS))
    lines = [HEADER, ":root {"]
    for key, c in data["color"].items():
        name = c.get("name", "")
        comment = f" /* {name} */" if name else ""
        lines.append(f"  --rw-{key}: {c['value']};{comment}")
    t = data["typography"]
    lines.append(f'  --rw-font-stack: {t["stack"]};')
    lines.append("  --rw-radius: 12px;")
    lines.append("}")
    lines.append("")
    css = "\n".join(lines)
    with open(OUT, "w") as f:
        f.write(css)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
